pipeline {
    agent { label 'testServer' }
// environment{
 //    DOCKER_HUB_CREDENTIALS = credentials('DOCKER_HUB_CRED')
  //   }
    stages {
        stage('checkout git branch') {
            steps {
      git credentialsId: 'github', url: 'https://github.com/dharma0907/vault.git'
                checkout scm
            }
        }
stage('docker build image') {
            // build docker image
            steps {
                sh "docker build --no-cache -t python-app-v${env.BUILD_NUMBER} -f cicd/Dockerfile ."
            }
        }
        stage('docker tag the build') {
            steps {
               
                sh "docker tag python-app-v${env.BUILD_NUMBER} demo.goharbor.io/py/pythonapp:v${env.BUILD_NUMBER}"    
            }
        }
        stage ('dockerlogin and  push  image to  repository') {
           steps {
                 withDockerRegistry([ credentialsId: "Harbor_cred", url: " https://demo.goharbor.io/ " ]) {
                  
                
                 sh "docker push demo.goharbor.io/py/pythonapp:v${env.BUILD_NUMBER}"
            }
          }
        }
        stage ('update helm release') {
            steps {
     sh "sudo /usr/local/bin/helm --kubeconfig /home/edureka/.kube/admin.conf  --install pythonapp --set image.tag='v${env.BUILD_NUMBER}' --namespace python -f cicd/charts"
            }
        }
}
}

