---
- hosts: test
  become: true
  become_user: root

  tasks:
  - name: install apitude using apt
    apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  - name: update
    apt:
       update_cache: yes
  - name: install dependencies
    apt:
       name: "{{item}}"
       state: present
       update_cache: yes
    loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-pip

  - name: Add Docker’s official GPG key
    apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present

  - name: adding repo docker
    apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu bionic stable
            state: present

  - name: Install docker
    apt:
      name: "{{item}}"
      state: latest
    loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
  - name: Install Docker Module for Python
    pip:
      name: docker
  - name: creating a container
    docker_container:
            name: sample
            image: hello-world
            state: present
  handlers:
  - name: restart docker
    service:
        name: docker
        state: restarted

